### ISSUE TITLE
[1.1.4] Flaky test: SessionTests.SessionLogsCacheRefreshException 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Session#187]
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Session.SessionTests.<SessionLogsCacheRefreshException>d__14.MoveNext() in /datadrive/teamcity/d6337ac2abf63a4b/.repositories/Session/test/Microsoft.AspNetCore.Session.Tests/SessionTests.cs:line 670
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by pranavkm** [comment]
cc @muratg

**Comment by muratg** [comment]
@jkotalik Could you take a look?

**Comment by jkotalik** [comment]
@pranavkm Was this test not flaky before 1.1.4? Also I'd assume you are referring to the rel/1.1.3 branch?

**Comment by Tratcher** [comment]
There were changes to it in dev. check the closed issues.

**Comment by jkotalik** [comment]
Seems the fix would be https://github.com/aspnet/Session/pull/143. Should I patch this in too?

**Comment by pranavkm** [comment]
Yup. If it's small enough (and test only) feel free to patch it in. You don't need to create a `rel/` branch for this change. If it requires src changes, consider skipping the test.
